name:               "Kenan"
description:        "PhD candidate"

url:                "https://kenanz0630.github.io"
author:             "kenanz0630"
email:              "zhangkenan0630@gmail.com"
gravatar_hash:      "de5c7e08016aeaa80d78eacbc33d60cc"
email:              "zhangkenan0630@gmail.com"
github:             "kenanz0630"
linkedin:           "kenan-zhang-5293972b"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          :year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "RESEARCH"
    href:           "research"
  - name:           "CV"
    href:           "cv"
  - name:           "BLOGS"
    href:           "blog"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
